### ISSUE TITLE
Caching doesn't work when using this image.

### ISSUE THREAD

**Issue by dessalines** [HaschekSolutions/PictShare-Docker#10]
Related issue: https://github.com/HaschekSolutions/pictshare/issues/99

To replicate:

`docker run -d -p 8123:80 --name=pictshare_another hascheksolutions/pictshare`

Goto http://localhost:8123, upload an image, then look at the response headers:

```
HTTP/1.1 200 OK
Server: nginx/1.14.2
Date: Sun, 20 Oct 2019 04:20:50 GMT
Content-Type: image/png
Transfer-Encoding: chunked
Connection: keep-alive
```

No etags, content-length, expires, etc.

**Comment by geek-at** [comment]
[fixed partially](https://github.com/HaschekSolutions/pictshare/issues/119) I'm still against caching (expire) headers from the platform itself because of the deletion process.

caching headers can be set in a reverse proxy on your side or on cloudflare
