### ISSUE TITLE
Upload forbidden

### ISSUE THREAD

**Issue by sudodrew** [HaschekSolutions/PictShare-Docker#18]
Upload forbidden
Due to configured restrictions, you are not allowed to upload files at this time

Updated my docker and got this.. not sure how to fix. Please help!

**Comment by geek-at** [comment]
are you using the ALLOWED_SUBNET parameter?

show me the starting command you're using to start the container

**Comment by geek-at** [comment]
found the bug. restart your container to update it and it should work

**Comment by sudodrew** [comment]
Wooho! Thanks so much its working again! =D
