### ISSUE TITLE
Always 404

### ISSUE THREAD

**Issue by abrahamturing** [HaschekSolutions/PictShare-Docker#8]
Today, one of containers moved from one node to another, and we started to get 404 occasionally. We redeployed the service but then it started to give always 404.

After digging into documentations, I have seen the following environment variable:

> AUTOUPDATE (true/false | should the container upgrade on every start? default: true)

I also observed that a new version is released recently, so I thought that a it might have broken something.

After digging into details more, I have observed [this commit](https://github.com/HaschekSolutions/PictShare-Docker/commit/55594f8a077619f9d0d6620923361b8bfcecc81a?diff=split#diff-3254677a7917c6c01f55212f86c57fbf), i.e. the image folder has changed from `/usr/share/nginx/html/upload` to `/usr/share/nginx/html/data`.

Since we mount our persistent volume as `upload`, it sucks.

If other people also face this problem, just fix mount paths. It should suffice.

By the way, I am turning off AUTOUPDATE 😈 .

**Comment by geek-at** [comment]
Right, that change was due to the complete rewrite for PictShare. Docs are updated. Sorry :)
